# Generated by Django 5.2.13 on 2026-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
