# Generated by Django 5.2.13 on 2026-04-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timeentry_rejection_comment_alter_timeentry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='rejection_comment',
        ),
    ]
