# Generated by Django 5.2.13 on 2026-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_timeentry_rejection_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('payroll_approved', 'Payroll Approved')], default='draft', max_length=20),
        ),
    ]
